/**
 * Created by ebundala on 6/12/2017.
 */
export const initialState = [
    "electronics",
    "Furniture",
    "Women's Apparel",
    "Women's shoes",
    "Men's shoes",
    "Men's Apparel",
    "Men's Watches",
    "Women's Watches",
    "Back Packs",
    "Books",
    "Automotive",
    "Computers",
    "Mobile Phones",
    "Accessories",
    "Jewelry",
    "electronics",
    "Furniture",
    "Women's Apparel",
    "Women's shoes",
    "Men's shoes",
    "Men's Apparel",
    "Men's Watches",
    "Women's Watches",
    "Back Packs",
    "Books",
    "Automotive",
    "Computers",
    "Mobile Phones",
    "Accessories",
    "Jewelry",

    "electronics",
    "Furniture",
    "Women's Apparel",
    "Women's shoes",
    "Men's shoes",
    "Men's Apparel",
    "Men's Watches",
    "Women's Watches",
    "Back Packs",
    "Books",
    "Automotive",
    "Computers",
    "Mobile Phones",
    "Accessories",
    "Jewelry",

    "electronics",
    "Furniture",
    "Women's Apparel",
    "Women's shoes",
    "Men's shoes",
    "Men's Apparel",
    "Men's Watches",
    "Women's Watches",
    "Back Packs",
    "Books",
    "Automotive",
    "Computers",
    "Mobile Phones",
    "Accessories",
    "Jewelry",
]

export const CATEGORY_ACTIONS={
    //Todo define actions for category
}